---
- hosts: localhost
  tasks:
    - name: Clean up the directory
      file: path=/tmp/k8s/conniedeploy state=absent

    - name: Create the tmp directory
      file: path=/tmp/k8s/conniedeploy state=directory

    - name: Render files template to /conniedeploy
      template: src={{ item }} dest=/tmp/k8s/conniedeploy/{{ item | basename }}
      with_fileglob: "{{playbook_dir}}/*.yml"
      # You can add extra conditional stuff here, example
      #when cluster_name in ["cluster1"]


    ###############################################################

    - name: Deploy Jira to K8s Cluste
      command: kubectl apply -f /tmp/k8s/conniedeploy

      # You can add extra conditional stuff here, example
      #when cluster_name in ["cluster1"]